// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "welcome": "مرحباً",
  "add_branch": "اضافة فرع جديد",
  "branch_name": "اسم الفرع",
  "full_address": "العنوان بالكامل",
  "enterAName": "أدخل اسمًا",
  "enterAnAddress": "أدخل العنوان",
  "enterAValidNumber": "أدخل رقمًا صالحًا",
  "selectLocation": "اختر موقعا",
  "addBranchManager": "اضافة مدير فرع",
  "gender": "الجنس",
  "male": "ذكر",
  "female": "أنثى",
  "firstName": "الاسم الأول",
  "lastName": "اسم العائلة",
  "email": "البريد الإلكتروني",
  "enterAnEmail": "أدخل بريدًا إلكترونيًا",
  "password": "كلمة المرور",
  "enterAPassword": "أدخل كلمة مرور تتكون من 6 أحرف على الأقل",
  "branchAdded": "تمت إضافة الفرع",
  "invalidEmail": "بريد إلكتروني غير صالح",
  "addBranchButton": "أضف الفرع",
  "selectBranch": "حدد الفرع",
  "managerAdded": "تمت إضافة مدير",
  "add": "اضف",
  "managerCanSignIn": "يمكن للمدير الآن تسجيل الدخول",
  "addNewDoctor": "اضافة طبيب جديد",
  "specialty": "التخصص",
  "enterASpecialty": "أدخل التخصص",
  "about": "عن الطبيب",
  "next": "التالي",
  "schedule": "الجدول",
  "admin": "المشرف",
  "appointmentsReport": "تقرير المواعيد",
  "today": "اليوم",
  "previous": "السابق",
  "upcoming": "القادم",
  "cancelled": "ملغى",
  "clients": "العملاء",
  "doctors": "الأطباء",
  "managers": "المديرين",
  "branches": "الفروع",
  "appointments": "مواعيد",
  "search": "بحث",
  "branchName": "اسم الفرع",
  "phoneNumber": "رقم الهاتف",
  "address": "العنوان",
  "manager": "المدير",
  "cancelAppointmentWarning": "هل أنت متأكد أنك تريد إلغاء هذا الموعد؟",
  "cancel": "إلغاء",
  "appointmentCancelled": "تم إلغاء الموعد",
  "yes": "نعم",
  "no": "لا",
  "chat": "محادثة",
  "disableBranchWarning1": "هل أنت متأكد أنك تريد تعطيل فرع",
  "disableBranchWarning2": "سيؤدي هذا إلى تعطيل جميع الأطباء والمديرين والمواعيد المرتبطة به",
  "branchDisabled": "تم تعطيل الفرع",
  "diasbleUserWarning": "هل أنت متأكد من أنك تريد تعطيل حساب",
  "userDisabled": "تم تعطيل الحساب",
  "editBranch": "تعديل الفرع",
  "selectManager": "حدد المدير",
  "editOnMap": "تعديل على الخريطة",
  "branchEdited": "تم تعديل الفرع",
  "edit": "عدل",
  "managerEdited": "تم تعديل المدير",
  "editDoctor": ".تعديل در",
  "doctorEdited": "تم تعديل الطبيب",
  "managerName": "اسم المدير",
  "branch": "الفرع",
  "editInfo": "تعديل",
  "booking": "الحجز",
  "canceling": "الإلغاء",
  "confirm": "تأكيد",
  "notifcationSettings": "إعدادات الإشعار",
  "language": "اللغة",
  "signOut": "تسجيل الخروج",
  "locationOnMap": "الموقع على الخريطة",
  "pleaseSelectALocation": "الرجاء تحديد موقع",
  "addManager": "أضف مدير",
  "notifications": "الإشعارات",
  "doctorName": "اسم الطبيب",
  "date": "التاريخ",
  "time": "الوقت",
  "bookAppointment": "احجز موعدًا",
  "selectDoctor": "الرجاء اختيار طبيب",
  "selectTimeSlot": "الرجاء اختيار وقت",
  "appointmentBooked": "تم حجز الموعد",
  "noTimeSlotSelected": "لم يتم تحديد وقت",
  "book": "احجز",
  "appointmentsRemaining": "مواعيد متبقية",
  "clientName": "اسم العميل",
  "age": "العمر",
  "doctorNotes": "ملاحظات الأطباء",
  "confirmDoctor": "تأكيد الطبيب",
  "myAccount": "حسابي",
  "registrationRequest": "طلب التسجيل",
  "enterAge": "أدخل العمر",
  "requestSent": "تم ارسال الطلب",
  "requestAwaitingApproval": "تم إرسال طلبك وينتظر الموافقة",
  "signIn": "تسجيل الدخول",
  "addNote": "اضف ملاحظة",
  "note": "ملاحظة",
  "insertANote": "أدخل ملاحظة",
  "acceptRequestQuestion": "هل أنت متأكد أنك تريد قبول طلب التسجيل هذا",
  "requestAccepted": "تم قبول الطلب",
  "addNewClient": "إضافة عميل جديد",
  "clientAdded": "تمت إضافة العميل",
  "clientCanSignIn": "يمكن للعميل الآن تسجيل الدخول",
  "selectClient": "الرجاء تحديد عميل",
  "selectDoctorFor": "الرجاء تحديد طبيب ل",
  "denyRequest": "هل أنت متأكد أنك تريد رفض هذا الطلب",
  "requestDenied": "تم رفض الطلب",
  "editSchedule": "تعديل الجدول",
  "clientEdited": "تم تعديل العميل",
  "chatWithbranch": "تحدث مع مدير فرع",
  "cantDeactivateManager": "لا يمكن تعطيل حساب المدير",
  "assignNewBoss": "يرجى تعيين مدير فرع جديد قبل تعطيل هذا"
};
static const Map<String,dynamic> en = {
  "welcome": "Welcome",
  "add_branch": "Add new branch",
  "branch_name": "Branch Name",
  "full_address": "Full Address",
  "enterAName": "Enter a name",
  "enterAnAddress": "Enter an address",
  "enterAValidNumber": "Enter a valid number",
  "selectLocation": "Select Location",
  "addBranchManager": "Add branch manager",
  "gender": "Gender",
  "male": "male",
  "female": "female",
  "firstName": "First Name",
  "lastName": "Last Name",
  "email": "Email",
  "enterAnEmail": "Enter an email",
  "password": "Password",
  "enterAPassword": "Enter a password 6+ characters long",
  "branchAdded": "Branch Added",
  "invalidEmail": "invalid email",
  "addBranchButton": "Add Branch",
  "selectBranch": "Select branch",
  "managerAdded": "Manager Added",
  "add": "Add",
  "managerCanSignIn": "Manager can now sign in",
  "addNewDoctor": "Add new doctor",
  "specialty": "Specialty",
  "enterASpecialty": "Enter a specialty",
  "about": "About",
  "next": "Next",
  "schedule": "Schedule",
  "admin": "Admin",
  "appointmentsReport": "Appointments Report",
  "today": "Today",
  "previous": "Previous",
  "upcoming": "Upcoming",
  "cancelled": "Canceled",
  "clients": "Clients",
  "doctors": "Doctors",
  "managers": "Managers",
  "branches": "Branches",
  "appointments": "Appointments",
  "search": "Search",
  "branchName": "Branch name",
  "phoneNumber": "Phone number",
  "address": "Address",
  "manager": "Manager",
  "cancelAppointmentWarning": "Are you sure you want to cancel this appointment ?",
  "cancel": "Cancel",
  "appointmentCancelled": "Appointment Canceled",
  "yes": "Yes",
  "no": "No",
  "chat": "Chat",
  "disableBranchWarning1": "Are you sure you want to disable",
  "disableBranchWarning2": "This will disable all doctors , managers , and appointments associated with it !",
  "branchDisabled": "Branch Disabled",
  "diasbleUserWarning": "Are you sure you want to disable",
  "userDisabled": "User Disabled",
  "editBranch": "Edit branch",
  "selectManager": "Select Manager",
  "editOnMap": "Edit on map",
  "branchEdited": "Branch Edited",
  "edit": "Edit",
  "managerEdited": "Manager Edited",
  "editDoctor": "Edit Dr.",
  "doctorEdited": "Doctor Edited",
  "managerName": "Manager Name",
  "branch": "Branch",
  "editInfo": "Edit info",
  "booking": "Booking",
  "canceling": "Canceling",
  "confirm": "Confirm",
  "notifcationSettings": "Notification Settings",
  "language": "Language",
  "signOut": "Sign out",
  "locationOnMap": "Location on map",
  "pleaseSelectALocation": "Please select a location",
  "addManager": "Add Manager",
  "notifications": "Notifications",
  "doctorName": "Doctor name",
  "date": "Date",
  "time": "Time",
  "bookAppointment": "Book Appointment",
  "selectDoctor": "Please select a doctor",
  "selectTimeSlot": "Please select a time slot",
  "appointmentBooked": "Appointment Booked",
  "noTimeSlotSelected": "No time slot was selected",
  "book": "Book",
  "appointmentsRemaining": "appointments remaining",
  "clientName": "Client name",
  "age": "Age",
  "doctorNotes": "Doctors notes",
  "confirmDoctor": "Confirm Doctor",
  "myAccount": "My Account",
  "registrationRequest": "Registration Request",
  "enterAge": "Enter an age",
  "requestSent": "Request Sent",
  "requestAwaitingApproval": "Your request is sent and awaiting approval",
  "signIn": "Sign in",
  "addNote": "Add Note",
  "note": "Note",
  "insertANote": "Insert a note",
  "acceptRequestQuestion": "Are you sure you want to accept this registration request",
  "requestAccepted": "Request Accepted",
  "addNewClient": "Add new client",
  "clientAdded": "Client Added",
  "clientCanSignIn": "Client can now sign in",
  "selectClient": "Please select a client",
  "selectDoctorFor": "Please select a doctor for",
  "denyRequest": "Are you sure you want to deny this request",
  "requestDenied": "Request Denied",
  "editSchedule": "Edit Schedule",
  "clientEdited": "Client Edited",
  "chatWithbranch": "Chat with a branch manager",
  "cantDeactivateManager": "Can't Deactivate Manager",
  "assignNewBoss": "Please assign a new branch manager before deactivating this one."
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
